name: custom_cached_network_image
description: "Custom cached Network Image"
version: 0.0.1

homepage: https://github.com/MehmetBarisKaya/custom_cached_network_image

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
 
flutter:  
  uses-material-design: true
 